FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json nest-cli.json ./
COPY apps/transactions-service ./apps/transactions-service
RUN npx nest build transactions-service

FROM node:22-alpine AS runtime
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
ENV NODE_ENV=production
COPY --from=build /app/dist/apps/transactions-service ./dist/apps/transactions-service
COPY drizzle.config.transactions-service.ts ./
COPY apps/transactions-service/drizzle ./apps/transactions-service/drizzle
COPY apps/transactions-service/src/db/schema.ts ./apps/transactions-service/src/db/schema.ts

EXPOSE 3000
CMD ["node", "dist/apps/transactions-service/main.js"]
